# Generated by Django 4.2.8 on 2024-02-28 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("equipment_image", models.ImageField(blank=True, null=True, upload_to="equipment_img/")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exercise_image", models.ImageField(blank=True, null=True, upload_to="exercise_img/")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("difficulty", models.CharField(max_length=25)),
                ("calories_burn", models.IntegerField()),
                ("custom_repeats", models.IntegerField()),
                ("time_required", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workout_image", models.ImageField(blank=True, null=True, upload_to="workout_img/")),
                ("name", models.CharField(max_length=100)),
                ("time_required", models.DurationField()),
                ("total_calories", models.IntegerField()),
                ("difficulty", models.CharField(max_length=20)),
                ("exercise_count", models.IntegerField(default=0)),
                ("equipments", models.ManyToManyField(to="workout.equipment")),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("set_count", models.IntegerField()),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workout.exercise")),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercise",
                        to="workout.workout",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(through="workout.WorkoutExercise", to="workout.exercise"),
        ),
        migrations.CreateModel(
            name="ExercisePerform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("header", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("step_no", models.IntegerField()),
                ("exercises", models.ManyToManyField(to="workout.exercise")),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("notification_note", models.TextField(blank=True)),
                ("notify_status", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")], default="Pending", max_length=15
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_schedule_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("workout", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workout.workout")),
            ],
            options={
                "unique_together": {("date", "time", "user")},
            },
        ),
    ]
