# Generated by Django 4.2.8 on 2024-02-18 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("difficulty", models.CharField(max_length=255)),
                ("calories_burn", models.IntegerField()),
                ("description", models.TextField()),
                ("repeat", models.IntegerField()),
                ("time", models.DurationField()),
            ],
            options={
                "ordering": ["difficulty"],
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("time", models.DurationField()),
                ("calories", models.IntegerField()),
                ("difficulty", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Workouts",
            },
        ),
        migrations.CreateModel(
            name="ExerciseSteps",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("steps_number", models.IntegerField()),
                ("steps_description", models.TextField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="workout.exercise"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="workout_exercises", to="workout.workout"
            ),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="equipments", to="workout.workout"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="exercise",
            unique_together={("name", "description")},
        ),
    ]
