# Generated by Django 4.2.8 on 2024-02-26 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("difficulty", models.CharField(max_length=25)),
                ("calories_burn", models.IntegerField()),
                ("custom_repeats", models.IntegerField()),
                ("time_required", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("time_required", models.DurationField()),
                ("calories_burn", models.IntegerField()),
                ("difficulty", models.CharField(max_length=20)),
                ("equipments", models.ManyToManyField(to="workout.equipment")),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("set_count", models.IntegerField()),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workout.exercise")),
                ("workout", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workout.workout")),
            ],
        ),
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(through="workout.WorkoutExercise", to="workout.exercise"),
        ),
    ]
