# Generated by Django 4.2.8 on 2024-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="exercise_count",
            field=models.IntegerField(default=0),
        ),
    ]
