# Generated by Django 4.2.8 on 2024-03-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="total_calories",
            field=models.IntegerField(default=0),
        ),
    ]
