# Generated by Django 4.2.8 on 2024-03-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0002_alter_workout_total_calories"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutschedule",
            name="check_notification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workoutschedule",
            name="send_notification",
            field=models.BooleanField(default=True),
        ),
    ]
