# Generated by Django 4.2.11 on 2024-03-31 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_ingredient_name_alter_nutrition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodschedule',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
