# Generated by Django 4.2.8 on 2024-02-27 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("cooking_difficulty", models.CharField(max_length=15)),
                ("time_required", models.PositiveIntegerField()),
                ("calories", models.PositiveIntegerField()),
                ("author", models.CharField(max_length=15)),
                ("description", models.TextField()),
                ("categories", models.ManyToManyField(to="meal.category")),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                ("food_count", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Nutrition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                ("quantity", models.FloatField()),
                ("property", models.CharField(max_length=15)),
                ("foods", models.ManyToManyField(to="meal.food")),
            ],
        ),
        migrations.CreateModel(
            name="MealStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("step_no", models.PositiveIntegerField()),
                ("food", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="meal.food")),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                ("quantity_required", models.CharField(max_length=15)),
                ("foods", models.ManyToManyField(to="meal.food")),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="foods",
            field=models.ManyToManyField(to="meal.meal"),
        ),
    ]
