# Generated by Django 4.2.8 on 2024-02-28 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_image", models.ImageField(blank=True, null=True, upload_to="category_img/")),
                ("name", models.CharField(max_length=25)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("food_image", models.ImageField(blank=True, null=True, upload_to="food_img/")),
                ("name", models.CharField(max_length=50)),
                ("cooking_difficulty", models.CharField(max_length=15)),
                ("time_required", models.PositiveIntegerField()),
                ("calories", models.PositiveIntegerField()),
                ("author", models.CharField(max_length=15)),
                ("description", models.TextField()),
                ("categories", models.ManyToManyField(to="meal.category")),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meal_image", models.ImageField(blank=True, null=True, upload_to="meal_img/")),
                ("name", models.CharField(max_length=25)),
                ("food_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Nutrition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nutrition_image", models.ImageField(blank=True, null=True, upload_to="nutrition_img/")),
                ("name", models.CharField(max_length=25)),
                ("quantity", models.FloatField()),
                ("property", models.CharField(max_length=15)),
                ("foods", models.ManyToManyField(to="meal.food")),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ingredient_image", models.ImageField(blank=True, null=True, upload_to="ingredient_img/")),
                ("name", models.CharField(max_length=25)),
                ("quantity_required", models.CharField(max_length=15)),
                ("foods", models.ManyToManyField(to="meal.food")),
            ],
        ),
        migrations.CreateModel(
            name="FoodMakingSteps",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("step_no", models.PositiveIntegerField()),
                ("food", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="meal.food")),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="foods",
            field=models.ManyToManyField(to="meal.meal"),
        ),
        migrations.CreateModel(
            name="FoodSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("notification_note", models.TextField(blank=True)),
                ("notify_status", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")], default="Pending", max_length=15
                    ),
                ),
                ("food", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="meal.food")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_schedule_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "time", "user")},
            },
        ),
    ]
