# Generated by Django 4.2.8 on 2024-02-24 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SensorData",
        ),
    ]
