# Generated by Django 4.2.8 on 2024-03-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="foods",
        ),
        migrations.RemoveField(
            model_name="nutrition",
            name="foods",
        ),
        migrations.AddField(
            model_name="food",
            name="ingredients",
            field=models.ManyToManyField(to="meal.ingredient"),
        ),
        migrations.AddField(
            model_name="food",
            name="nutritions",
            field=models.ManyToManyField(to="meal.nutrition"),
        ),
        migrations.AddField(
            model_name="meal",
            name="categorys",
            field=models.ManyToManyField(to="meal.category"),
        ),
        migrations.AlterField(
            model_name="category",
            name="foods",
            field=models.ManyToManyField(to="meal.food"),
        ),
    ]
