# Generated by Django 4.2.8 on 2024-03-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0003_foodschedule_check_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodschedule",
            name="send_notification",
            field=models.BooleanField(default=True),
        ),
    ]
