# Generated by Django 4.2.8 on 2023-12-07 09:37

from django.db import migrations, models
import fitnesswithai.users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", fitnesswithai.users.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="social_auth",
            field=models.CharField(
                blank=True,
                choices=[("GOOGLE", "GOOGLE"), ("FACEBOOK", "FACEBOOK")],
                help_text="This field indicates through which social app has user logged in or signup",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("USER", "USER"), ("PRO-USER", "PRO-USER")], default="USER", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email Address"),
        ),
    ]
