# Generated by Django 4.2.11 on 2024-03-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='food',
            name='nutritions',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity_required',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='property',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='quantity',
        ),
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('property', models.CharField(max_length=15)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.food')),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.nutrition')),
            ],
            options={
                'unique_together': {('food', 'nutrition')},
            },
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.CharField(max_length=15)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.food')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.ingredient')),
            ],
            options={
                'unique_together': {('food', 'ingredient')},
            },
        ),
    ]
