# Generated by Django 4.2.8 on 2024-02-16 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_user_email_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("avatar", models.TextField(default="fitnestx/static/images/avator/default.png")),
                ("gender", models.CharField(max_length=10, null=True)),
                ("dob", models.DateField(null=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("goal", models.CharField(max_length=15, null=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
    ]
