# Generated by Django 4.2.8 on 2024-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="First Name of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Last Name of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, verbose_name="Username of User"),
        ),
    ]
