# Generated by Django 4.2.8 on 2024-02-28 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterIntake",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_time", models.DateTimeField()),
                ("quantity", models.PositiveIntegerField()),
                ("notify", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SleepTracking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sleep_start_time", models.DateTimeField()),
                ("sleep_end_time", models.DateTimeField()),
                ("sleep_duration", models.DurationField()),
                ("sleep_quality", models.CharField(max_length=10)),
                ("notify", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleep_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField()),
                ("date_and_time", models.DateTimeField()),
                ("predicted_activity", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("calories_burn", models.PositiveIntegerField(default=0)),
                ("target_calories_burn", models.PositiveIntegerField(default=0)),
                ("calories_burn_complete_staus", models.BooleanField(default=False)),
                ("steps", models.PositiveIntegerField(default=0)),
                ("target_steps", models.PositiveIntegerField(default=0)),
                ("steps_complete_staus", models.BooleanField(default=False)),
                ("running_distance", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("target_running_distance", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("running_distance_complete_staus", models.BooleanField(default=False)),
                ("flights_climbed", models.PositiveIntegerField(default=0)),
                ("target_flights_climbed", models.PositiveIntegerField(default=0)),
                ("flights_climbed_complete_staus", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
