# Generated by Django 4.2.8 on 2024-02-25 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_id", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ActivityGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calories_burn", models.PositiveIntegerField(default=0)),
                ("steps", models.PositiveIntegerField(default=0)),
                ("running_distance", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("flights_climbed", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
